version: "3.9"
services:
  nuxt:
    build:
      context: .
      # ใช้ stage runner (default ใน Dockerfile คือ stage สุดท้ายอยู่แล้ว)
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    restart: unless-stopped
